application: giflord
version: 5
runtime: python27
api_version: 1
threadsafe: no

inbound_services:
- warmup

libraries:
- name: PIL
  version: latest

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /static
  static_dir: static

- url: /.*
  script: main.py
